### ISSUE TITLE
Allow setting `debug` through config.exs

### ISSUE THREAD

**Issue by alexlafroscia** [Financial-Times/tapper_plug#1]
I think it might be useful to allow a user to set the `debug` flag through their `config.exs`.  For example, I might want to set this in dev, to keep an eye on during development, but keep it off in production.

I think I can pull this off right now by doing something like:

```exs
# config/dev.exs
config :tapper,
  debug: true,
  system_id: "whatever"
```

```ex
# endpoint
plug Tapper.Plug.Tracer, debug: Application.get_env(:tapper, :debug, false)
```

but a built-in solution would be really nice!

**Comment by alexlafroscia** [comment]
BTW if this is something you'd be amenable too I wouldn't mind making the PR myself

**Comment by ellispritchard** [comment]
Go for it!

**Comment by ellispritchard** [comment]
Implemented.

**Comment by alexlafroscia** [comment]
Sorry, I kinda got away from the project I was using this and forgot I'd offered to try it myself. Thanks for doing this!
