### ISSUE TITLE
Support for tapper contextual API

### ISSUE THREAD

**Issue by indrekj** [Financial-Times/tapper_plug#3]
Hello,

I'm trying to add zipkin support to our elixir applications. I can use Tapper.Plug.Trace to start a trace on incoming HTTP request. I also want to propagate this state to outgoing HTTP requests. I'm currently creating a plug to Tesla to add trace information to headers https://github.com/salemove/elixir-tesla_middleware_tapper/pull/1 . I'm taking an advantage of the tapper contextual API. It however seems that Tapper.Plug doesn't support contextual API. What's the best practice to get trace information from Tapper.Plug.Trace to the HTTP client?

One idea I can see is to create another Plug to get the trace information from the connection and then store it using the contextual API. Is there something better? Could we add Contextual API support to this library as well?

**Comment by ellispritchard** [comment]
Yes, there's currently no direct support in `Tapper.Plug` for populating the context, but it would be easy to extend the plug to allow this as an option; it should probably remove the context after it has handled the request.

Happy to receive a PR for this. 😃

**Comment by indrekj** [comment]
@ellispritchard comments are welcome https://github.com/Financial-Times/tapper_plug/pull/4
